2016-11-03 21:36:43,508 | INFO     | log.py               (128) | setupLogging | Choosing RAET log level 1
2016-11-03 21:36:46,055 | DEBUG    | testable.py          (126) | decorator | in SpyableTestClient added spy on __init__
2016-11-03 21:36:46,055 | WARNING  | testable.py          (134) | decorator | method <function Client.handleOneNodeMsg at 0x7fc0645b8ea0> not found, so no spy added
2016-11-03 21:36:46,078 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on __init__
2016-11-03 21:36:46,078 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterReqLatencyTooHigh
2016-11-03 21:36:46,078 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterThroughputTooLow
2016-11-03 21:36:46,085 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on sendThroughput
2016-11-03 21:36:46,092 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on __init__
2016-11-03 21:36:46,092 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on catchupCompleted
2016-11-03 21:36:46,092 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on processConsistencyProofReq
2016-11-03 21:36:46,092 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on startCatchUpProcess
2016-11-03 21:36:46,101 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on __init__
2016-11-03 21:36:46,103 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on addToPrePrepares
2016-11-03 21:36:46,103 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canProcessPrePrepare
2016-11-03 21:36:46,103 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canSendPrepare
2016-11-03 21:36:46,103 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doOrder
2016-11-03 21:36:46,104 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrePrepare
2016-11-03 21:36:46,104 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrepare
2016-11-03 21:36:46,104 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on isValidPrepare
2016-11-03 21:36:46,104 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on orderPendingCommit
2016-11-03 21:36:46,104 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processCommit
2016-11-03 21:36:46,104 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrePrepare
2016-11-03 21:36:46,104 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrepare
2016-11-03 21:36:46,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on __init__
2016-11-03 21:36:46,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on checkPerformance
2016-11-03 21:36:46,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on decidePrimaries
2016-11-03 21:36:46,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on discard
2016-11-03 21:36:46,116 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on eatTestMsg
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on forward
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleInvalidClientMsg
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleOneNodeMsg
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToClientInBox
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToNodeInBox
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processInstanceChange
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processOrdered
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processPropagate
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processRequest
2016-11-03 21:36:46,118 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on propagate
2016-11-03 21:36:46,118 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousClient
2016-11-03 21:36:46,118 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousNode
2016-11-03 21:36:46,118 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on send
2016-11-03 21:36:46,118 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on sendInstanceChange
2016-11-03 21:36:46,118 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on startViewChange
Loading module /home/lovesh/.virtualenvs/sovrin-dev/lib/python3.5/site-packages/anoncreds_dev-0.1.8-py3.5.egg/config/config-crypto-example1.py
Module loaded.
2016-11-03 21:36:46,634 | DEBUG    | gen_load_ratcheting  (280) | main | Results file: /home/lovesh/dev/evernym/sovrin-priv/scripts/perf_results_1_2_1478189206.csv
2016-11-03 21:36:46,639 | INFO     | gen_load_ratcheting  (136) | _spawnClient | Seed for client Claaaa2 is b'0000000000000000000000000Claaaa2', its len is 32
2016-11-03 21:36:46,640 | DEBUG    | ledger.py            (164) | start | Starting ledger...
2016-11-03 21:36:46,640 | DEBUG    | ledger.py            (69) | recoverTree | Recovering tree from transaction log
2016-11-03 21:36:46,675 | INFO     | client.py            (121) | __init__ | Client Claaaa2 initialized with the following node registry:
2016-11-03 21:36:46,675 | INFO     | client.py            (128) | __init__ |     EvernymV1C      listens at 52.33.22.91    on port 9722
2016-11-03 21:36:46,675 | INFO     | client.py            (128) | __init__ |     EvernymV2C      listens at 52.38.24.189   on port 9724
2016-11-03 21:36:46,675 | INFO     | client.py            (128) | __init__ |     WSECUC          listens at 13.93.218.255  on port 9726
2016-11-03 21:36:46,675 | INFO     | client.py            (128) | __init__ |     BIGC            listens at 52.160.103.164 on port 9728
2016-11-03 21:36:46,675 | INFO     | client.py            (128) | __init__ |     RespectNetworkC listens at 54.173.9.185   on port 9730
2016-11-03 21:36:46,675 | INFO     | client.py            (128) | __init__ |     FCUC            listens at 69.144.146.171 on port 9734
2016-11-03 21:36:46,675 | INFO     | client.py            (128) | __init__ |     BYUC            listens at 54.193.6.155   on port 9745
2016-11-03 21:36:46,675 | DEBUG    | plugin_helper.py     (25) | loadPlugins | Plugin loading started to load plugins from basedir: /home/lovesh/.sovrin
2016-11-03 21:36:47,303 | DEBUG    | plugin_helper.py     (68) | loadPlugins | Total plugins loaded from basedir /home/lovesh/.sovrin are : 1
2016-11-03 21:36:47,303 | DEBUG    | client.py            (148) | __init__ | total plugins loaded in client: 1
2016-11-03 21:36:47,303 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
2016-11-03 21:36:47,304 | DEBUG    | looper.py            (121) | __init__ | Setting handler for SIGINT
2016-11-03 21:36:47,304 | DEBUG    | motor.py             (34) | set_status | Claaaa2 changing status from stopped to starting
2016-11-03 21:36:47,304 | INFO     | stacked.py           (75) | start | stack Claaaa2 starting at ('0.0.0.0', 6514) in always mode
2016-11-03 21:36:47,304 | INFO     | stacked.py           (851) | start | Claaaa2 listening for other nodes at 0.0.0.0:6514
2016-11-03 21:36:47,304 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa2 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:47,304 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa2 nodestack is []
2016-11-03 21:36:47,304 | DEBUG    | stacked.py           (504) | connectToMissing | Claaaa2 found the following missing connections: EvernymV2C, RespectNetworkC, BYUC, FCUC, EvernymV1C, WSECUC, BIGC
2016-11-03 21:36:47,359 | INFO     | stacked.py           (456) | connect | Claaaa2 looking for EvernymV2C at 52.38.24.189:9724
2016-11-03 21:36:47,412 | INFO     | stacked.py           (456) | connect | Claaaa2 looking for RespectNetworkC at 54.173.9.185:9730
2016-11-03 21:36:47,469 | INFO     | stacked.py           (456) | connect | Claaaa2 looking for BYUC at 54.193.6.155:9745
2016-11-03 21:36:47,909 | INFO     | stacked.py           (456) | connect | Claaaa2 looking for FCUC at 69.144.146.171:9734
2016-11-03 21:36:47,927 | INFO     | stacked.py           (456) | connect | Claaaa2 looking for EvernymV1C at 52.33.22.91:9722
2016-11-03 21:36:47,979 | INFO     | stacked.py           (456) | connect | Claaaa2 looking for WSECUC at 13.93.218.255:9726
2016-11-03 21:36:47,998 | INFO     | stacked.py           (456) | connect | Claaaa2 looking for BIGC at 52.160.103.164:9728
2016-11-03 21:36:47,998 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa2 next check for retries in 6.00 seconds
2016-11-03 21:36:48,002 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa2'. Stale transaction '1' packet 'None' from '('54.193.6.155', 9745)' in 1 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '0'
Staler 'Claaaa2'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 1 at 1.68911320999905
2016-11-03 21:36:48,378 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa2'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '0'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.709279233997222
Staler 'Claaaa2'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '0'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.709279233997222
Staler 'Claaaa2'. Stale transaction '1' packet 'None' from '('54.173.9.185', 9730)' in 1 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '0'
Staler 'Claaaa2'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 1 at 1.709279233997222
2016-11-03 21:36:48,760 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:48,897 | DEBUG    | stacked.py           (294) | conns | Claaaa2's connection changed from set() to {'BYUC'}
2016-11-03 21:36:48,897 | INFO     | stacked.py           (320) | _connsChanged | Claaaa2 now connected to BYUC
2016-11-03 21:36:48,897 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa2 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BYUC
2016-11-03 21:36:48,935 | DEBUG    | stacked.py           (294) | conns | Claaaa2's connection changed from {'BYUC'} to {'RespectNetworkC', 'BYUC'}
2016-11-03 21:36:48,936 | INFO     | stacked.py           (320) | _connsChanged | Claaaa2 now connected to RespectNetworkC
2016-11-03 21:36:48,936 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa2 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to RespectNetworkC
Staler 'Claaaa2'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '0'
Staler 'Claaaa2'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.3592836030002218
2016-11-03 21:36:49,051 | DEBUG    | stacked.py           (294) | conns | Claaaa2's connection changed from {'RespectNetworkC', 'BYUC'} to {'RespectNetworkC', 'EvernymV1C', 'BYUC'}
2016-11-03 21:36:49,051 | INFO     | stacked.py           (320) | _connsChanged | Claaaa2 now connected to EvernymV1C
2016-11-03 21:36:49,051 | DEBUG    | motor.py             (34) | set_status | Claaaa2 changing status from starting to started_hungry
2016-11-03 21:36:49,051 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa2 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV1C
2016-11-03 21:36:49,083 | DEBUG    | stacked.py           (294) | conns | Claaaa2's connection changed from {'RespectNetworkC', 'EvernymV1C', 'BYUC'} to {'EvernymV2C', 'RespectNetworkC', 'EvernymV1C', 'BYUC'}
2016-11-03 21:36:49,083 | INFO     | stacked.py           (320) | _connsChanged | Claaaa2 now connected to EvernymV2C
2016-11-03 21:36:49,083 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa2 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV2C
2016-11-03 21:36:49,137 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa2'. Stale transaction '3' packet '1' from '('54.193.6.155', 9745)' in 2 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '438'
Staler 'Claaaa2'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 2 at 2.4935832060000394
Staler 'Claaaa2'. Stale transaction '3' packet '1' from '('54.173.9.185', 9730)' in 2 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '477'
Staler 'Claaaa2'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 2 at 2.51457575999666
Staler 'Claaaa2'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '0'
Staler 'Claaaa2'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.570625462998578
2016-11-03 21:36:49,293 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa2 got msg from node RespectNetworkC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,293 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa2 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from RespectNetworkC
2016-11-03 21:36:49,294 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa2 cannot start catchup since received only 1 consistency proofs but need at least 3
2016-11-03 21:36:49,308 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa2 got msg from node BYUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,309 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa2 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BYUC
2016-11-03 21:36:49,309 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa2 scheduling action functools.partial(<bound method LedgerManager.checkIfCPsNeeded of Claaaa2>, 0) with id 1 to run in 30 seconds
2016-11-03 21:36:49,309 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa2 cannot start catchup since received only 2 consistency proofs but need at least 3
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('54.193.6.155', 9745)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '438'
Staler 'Claaaa2'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 3 at 2.7136924880032893
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('54.173.9.185', 9730)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '477'
Staler 'Claaaa2'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 3 at 2.7698669039964443
Staler 'Claaaa2'. Stale transaction '3' packet '1' from '('52.33.22.91', 9722)' in 2 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '470'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 2 at 2.797881027996482
2016-11-03 21:36:49,515 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
2016-11-03 21:36:49,608 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa2 got msg from node EvernymV1C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,608 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa2 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV1C
2016-11-03 21:36:49,609 | DEBUG    | ledger_manager.py    (576) | canStartCatchUpProcess | Claaaa2 deciding on the basis of CPs {'RespectNetworkC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'EvernymV1C': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'BYUC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='])} and f 1
2016-11-03 21:36:49,609 | DEBUG    | ledger_manager.py    (656) | startCatchUpProcess | Claaaa2 started catching up with consistency proof CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=('Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='))
2016-11-03 21:36:49,609 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa2 scheduling action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa2>, 0) with id 2 to run in 5.1 seconds
2016-11-03 21:36:49,609 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa2 sending msg OrderedDict([('op', 'CATCHUP_REQ'), ('ledgerType', 0), ('seqNoStart', 8), ('seqNoEnd', 8)]) to EvernymV2C
Staler 'Claaaa2'. Stale transaction '3' packet '1' from '('52.38.24.189', 9724)' in 2 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '486'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 2 at 2.9488339640010963
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('52.33.22.91', 9722)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '470'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 3 at 2.990496614998847
2016-11-03 21:36:49,679 | DEBUG    | stacked.py           (294) | conns | Claaaa2's connection changed from {'EvernymV2C', 'RespectNetworkC', 'EvernymV1C', 'BYUC'} to {'EvernymV2C', 'RespectNetworkC', 'FCUC', 'EvernymV1C', 'BYUC'}
2016-11-03 21:36:49,679 | INFO     | stacked.py           (320) | _connsChanged | Claaaa2 now connected to FCUC
2016-11-03 21:36:49,679 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa2 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to FCUC
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('52.38.24.189', 9724)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '486'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 3 at 3.055185614997754
2016-11-03 21:36:49,746 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa2 got msg from node EvernymV2C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,747 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa2 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV2C
2016-11-03 21:36:49,747 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa2 cannot process consistency proof since in state 2 and canSync is True
2016-11-03 21:36:49,892 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa2'. Stale transaction '3' packet '1' from '('69.144.146.171', 9734)' in 2 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '339'
Staler 'Claaaa2'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 2 at 3.232858811003098
2016-11-03 21:36:49,954 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa2 got msg from node EvernymV2C: {'op': 'CATCHUP_REP', 'ledgerType': 0, 'txns': {'8': {'reqId': 1478156921805694, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'client_port': 9726, 'node_ip': '40.121.149.41', 'alias': 'WSECU'}, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'type': 'CHANGE_HA', 'txnTime': 1478157003369.697}}, 'consProof': []}
2016-11-03 21:36:49,955 | DEBUG    | ledger_manager.py    (384) | processCatchupRep | Claaaa2 received catchup reply from EvernymV2C: CATCHUP_REP(ledgerType=0, txns={'8': {'reqId': 1478156921805694, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'client_port': 9726, 'node_ip': '40.121.149.41', 'alias': 'WSECU'}, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'type': 'CHANGE_HA', 'txnTime': 1478157003369.697}}, consProof=[])
2016-11-03 21:36:49,955 | DEBUG    | ledger_manager.py    (390) | processCatchupRep | Claaaa2 found 1 transactions in the catchup from EvernymV2C
2016-11-03 21:36:49,955 | DEBUG    | ledger_manager.py    (399) | processCatchupRep | Claaaa2 merging all received catchups
2016-11-03 21:36:49,955 | DEBUG    | ledger_manager.py    (405) | processCatchupRep | Claaaa2 merged catchups, there are 1 of them now, from 8 to 8
2016-11-03 21:36:49,955 | DEBUG    | ledger_manager.py    (496) | hasValidCatchupReplies | Claaaa2 verifying proof for 8, 8, b'\xc8v\xe37\xc5\xb5\xf0S\x827m\x9d\xe9\xbf\x8b\xc9\xc4\xd7\xaf)\x0b\xb5\xfa\x06\x90\xb1Ed\xb8\xb9ya', b'\xd7\x99p\xfar\xf5\xd9\x9e\xb8\xd2\x05\xe3\x81\x9f\x8c\xdd2;\xfd\xab(\xf6\xbcU\tNW\xc0jDMV', []
2016-11-03 21:36:49,955 | INFO     | ledger_manager.py    (505) | hasValidCatchupReplies | Claaaa2 could not verify catchup reply CATCHUP_REP(ledgerType=0, txns={'8': {'reqId': 1478156921805694, 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'client_port': 9726, 'node_ip': '40.121.149.41', 'alias': 'WSECU'}, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'type': 'CHANGE_HA', 'txnTime': 1478157003369.697}}, consProof=[]) since Inconsistency: different root hashes for the same tree size
2016-11-03 21:36:49,955 | DEBUG    | ledger_manager.py    (413) | processCatchupRep | Claaaa2 processed 0 catchup replies with sequence numbers []
2016-11-03 21:36:50,031 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa2 got msg from node FCUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:50,031 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa2 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from FCUC
2016-11-03 21:36:50,031 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa2 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('69.144.146.171', 9734)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '339'
Staler 'Claaaa2'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 3 at 3.5616568390032626
2016-11-03 21:36:50,268 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:50,646 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,029 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,405 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,783 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,160 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa2'. Stale transaction '1' packet 'None' from '('52.160.103.164', 9728)' in 1 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '0'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 1 at 5.534983352998097
2016-11-03 21:36:52,536 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,912 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,288 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,307 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa2 join already in process, so waiting to check for reconnects
2016-11-03 21:36:53,307 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Claaaa2 allow already in process, so waiting to check for reconnects
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa2 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa2 nodestack is ['EvernymV2C', 'RespectNetworkC', 'BYUC', 'FCUC', 'EvernymV1C', 'estate_85a08e69a1df11e6ac2c6807152028e4', 'BIGC']
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 2 ('52.38.24.189', 9724)
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 3 ('54.173.9.185', 9730)
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 4 ('54.193.6.155', 9745)
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 5 ('69.144.146.171', 9734)
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 6 ('52.33.22.91', 9722)
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa2 unmatched remote is 7 ('13.93.218.255', 9726)
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa2 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_85a08e69a1df11e6ac2c6807152028e4
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 8 ('52.160.103.164', 9728)
2016-11-03 21:36:53,308 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa2 next check for retries in 6.00 seconds
2016-11-03 21:36:53,664 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,041 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,418 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,720 | DEBUG    | has_action_queue.py  (60) | _serviceActions | Claaaa2 running action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa2>, 0) with id 2
2016-11-03 21:36:54,794 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:55,171 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:55,498 | DEBUG    | stacked.py           (294) | conns | Claaaa2's connection changed from {'EvernymV2C', 'RespectNetworkC', 'FCUC', 'EvernymV1C', 'BYUC'} to {'BYUC', 'FCUC', 'EvernymV1C', 'EvernymV2C', 'RespectNetworkC', 'BIGC'}
2016-11-03 21:36:55,498 | INFO     | stacked.py           (320) | _connsChanged | Claaaa2 now connected to BIGC
2016-11-03 21:36:55,498 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa2 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BIGC
2016-11-03 21:36:55,547 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 6 / 7 nodes
2016-11-03 21:36:55,547 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkIfConnectedToAll) succeeded with -0.05 seconds to spare
2016-11-03 21:36:55,548 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'reqId': 1478189215548062, 'operation': {'type': 'ATTRIB', 'raw': '78ec9dcf1093bbfc37a3381718b13b8ca5aa9ca526768afcdb825187072b600e'}, 'signature': None, 'identifier': '9FtZrWbGvn7AGNvqbGqnVWZwmrY4AfX2Gj2EHZ9xdSVV'} into identifier:9FtZrWbGvn7AGNvqbGqnVWZwmrY4AfX2Gj2EHZ9xdSVV|operation:raw:78ec9dcf1093bbfc37a3381718b13b8ca5aa9ca526768afcdb825187072b600e|type:ATTRIB|reqId:1478189215548062
2016-11-03 21:36:55,548 | DEBUG    | client.py            (228) | submitReqs | Claaaa2 pending request since in mode 1 and connected to {'BYUC', 'FCUC', 'EvernymV1C', 'EvernymV2C', 'RespectNetworkC', 'BIGC'} nodes
2016-11-03 21:36:55,548 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'type': 'ATTRIB', 'raw': '{"irdXCW614QpnJE5zsTjP_232740": "709812648345_IXR5qaPUKN3EepCnsvQVfl9z6mYik0BHoTOLjyZbt78FrxcugW"}'}, 'identifier': '9FtZrWbGvn7AGNvqbGqnVWZwmrY4AfX2Gj2EHZ9xdSVV', 'reqId': 1478189215548062, 'signature': 'XufpYNcUMJrxsGQdXBArnCFniHnsTvE1NTeVnLgXhXYnjo1xRZvC3VP566fizfsCeViRnKztQrKEfVmDX2BGCZb'}
2016-11-03 21:36:55,549 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa2 sending request Request: {'operation': {'type': 'ATTRIB', 'raw': '{"irdXCW614QpnJE5zsTjP_232740": "709812648345_IXR5qaPUKN3EepCnsvQVfl9z6mYik0BHoTOLjyZbt78FrxcugW"}'}, 'identifier': '9FtZrWbGvn7AGNvqbGqnVWZwmrY4AfX2Gj2EHZ9xdSVV', 'reqId': 1478189215548062, 'signature': 'XufpYNcUMJrxsGQdXBArnCFniHnsTvE1NTeVnLgXhXYnjo1xRZvC3VP566fizfsCeViRnKztQrKEfVmDX2BGCZb'}
Staler 'Claaaa2'. Stale transaction '3' packet '1' from '('52.160.103.164', 9728)' in 2 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '479'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 2 at 10.86000590799813
2016-11-03 21:36:59,317 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa2 join already in process, so waiting to check for reconnects
2016-11-03 21:36:59,317 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa2 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:59,317 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa2 nodestack is ['EvernymV2C', 'RespectNetworkC', 'BYUC', 'FCUC', 'EvernymV1C', 'estate_85a08e69a1df11e6ac2c6807152028e4', 'BIGC']
2016-11-03 21:36:59,317 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 2 ('52.38.24.189', 9724)
2016-11-03 21:36:59,318 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 3 ('54.173.9.185', 9730)
2016-11-03 21:36:59,318 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 4 ('54.193.6.155', 9745)
2016-11-03 21:36:59,318 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 5 ('69.144.146.171', 9734)
2016-11-03 21:36:59,318 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 6 ('52.33.22.91', 9722)
2016-11-03 21:36:59,318 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa2 unmatched remote is 7 ('13.93.218.255', 9726)
2016-11-03 21:36:59,318 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa2 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_85a08e69a1df11e6ac2c6807152028e4
2016-11-03 21:36:59,318 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 8 ('52.160.103.164', 9728)
2016-11-03 21:36:59,319 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa2 next check for retries in 6.00 seconds
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '479'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.646166719998291
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '479'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.646166719998291
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '479'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.646166719998291
2016-11-03 21:37:00,637 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa2', signerId='9FtZrWbGvn7AGNvqbGqnVWZwmrY4AfX2Gj2EHZ9xdSVV', reqId=1478189215548062, transactionType='ATTRIB', sentAt=1478189215.5486805, quorumAt='', latency=5.089173316955566, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:00,638 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.41 seconds to spare
2016-11-03 21:37:00,638 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 5.090550184249878
        Average latency: 5.089173316955566
        Throughput: 0.0
        Error rate: 0.19644242052538685
        Succeeded: 0
        Failed: 1
        Query Time: 0
        ================================
        
2016-11-03 21:37:00,638 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'reqId': 1478189220638593, 'operation': {'type': 'ATTRIB', 'raw': 'aa3e5fce0ec32c0a444d1327c609189753bdbac3e8fe06f900a488f4a4af386e'}, 'signature': None, 'identifier': '9FtZrWbGvn7AGNvqbGqnVWZwmrY4AfX2Gj2EHZ9xdSVV'} into identifier:9FtZrWbGvn7AGNvqbGqnVWZwmrY4AfX2Gj2EHZ9xdSVV|operation:raw:aa3e5fce0ec32c0a444d1327c609189753bdbac3e8fe06f900a488f4a4af386e|type:ATTRIB|reqId:1478189220638593
2016-11-03 21:37:00,638 | DEBUG    | client.py            (228) | submitReqs | Claaaa2 pending request since in mode 1 and connected to {'BYUC', 'FCUC', 'EvernymV1C', 'EvernymV2C', 'RespectNetworkC', 'BIGC'} nodes
2016-11-03 21:37:00,638 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'type': 'ATTRIB', 'raw': '{"j3iV0S1URfOQDa92H8Co_818783": "111943304096_YcVF1zAfk5eKyuOrPbECL4odqTs63ZhgxBM7JDXNwIiU8nvaRW"}'}, 'identifier': '9FtZrWbGvn7AGNvqbGqnVWZwmrY4AfX2Gj2EHZ9xdSVV', 'reqId': 1478189220638593, 'signature': '3Dp7X63qgNY5JBHxNoxSNwJSeBzeSNsYbgKfcKek7QxTh57p3cASPBD56AQdhuCEXArW1oWbJrRqKbrPE5FoEpKs'}
2016-11-03 21:37:00,639 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa2 sending request Request: {'operation': {'type': 'ATTRIB', 'raw': '{"j3iV0S1URfOQDa92H8Co_818783": "111943304096_YcVF1zAfk5eKyuOrPbECL4odqTs63ZhgxBM7JDXNwIiU8nvaRW"}'}, 'identifier': '9FtZrWbGvn7AGNvqbGqnVWZwmrY4AfX2Gj2EHZ9xdSVV', 'reqId': 1478189220638593, 'signature': '3Dp7X63qgNY5JBHxNoxSNwJSeBzeSNsYbgKfcKek7QxTh57p3cASPBD56AQdhuCEXArW1oWbJrRqKbrPE5FoEpKs'}
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '479'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 14.836295303000952
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '479'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 14.836295303000952
2016-11-03 21:37:01,531 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa2 got msg from node BIGC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:37:01,531 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa2 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BIGC
2016-11-03 21:37:01,532 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa2 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa2'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa2'. Unknown correspondent estate id '479'
Staler 'Claaaa2'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 15.411707626000862
Stalent 'Claaaa2'. Stale transaction '0' packet '0' from '('52.160.103.164', 9728)' in 1 nacking ...
Stalent 'Claaaa2'. Unknown initiator estate id '479'
Stalent 'Claaaa2'. Do Nack of ('52.160.103.164', 9728) in 1 at 15.411707626000862
2016-11-03 21:37:05,318 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa2 join already in process, so waiting to check for reconnects
2016-11-03 21:37:05,318 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa2 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:37:05,318 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa2 nodestack is ['EvernymV2C', 'RespectNetworkC', 'BYUC', 'FCUC', 'EvernymV1C', 'estate_85a08e69a1df11e6ac2c6807152028e4', 'BIGC']
2016-11-03 21:37:05,319 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 2 ('52.38.24.189', 9724)
2016-11-03 21:37:05,319 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 3 ('54.173.9.185', 9730)
2016-11-03 21:37:05,319 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 4 ('54.193.6.155', 9745)
2016-11-03 21:37:05,319 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 5 ('69.144.146.171', 9734)
2016-11-03 21:37:05,319 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 6 ('52.33.22.91', 9722)
2016-11-03 21:37:05,319 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa2 unmatched remote is 7 ('13.93.218.255', 9726)
2016-11-03 21:37:05,319 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa2 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_85a08e69a1df11e6ac2c6807152028e4
2016-11-03 21:37:05,319 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa2 matched remote is 8 ('52.160.103.164', 9728)
2016-11-03 21:37:05,319 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa2 next check for retries in 6.00 seconds
2016-11-03 21:37:05,672 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa2', signerId='9FtZrWbGvn7AGNvqbGqnVWZwmrY4AfX2Gj2EHZ9xdSVV', reqId=1478189220638593, transactionType='ATTRIB', sentAt=1478189220.6388783, quorumAt='', latency=5.033209800720215, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:05,672 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.47 seconds to spare
2016-11-03 21:37:05,672 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 10.124953508377075
        Average latency: 5.061191558837891
        Throughput: 0.0
        Error rate: 0.1975317712170492
        Succeeded: 0
        Failed: 2
        Query Time: 0
        ================================
        
2016-11-03 21:37:05,672 | DEBUG    | gen_load_ratcheting  (326) | main | Sent 1 ATTRIB requests
2016-11-03 21:37:05,673 | INFO     | looper.py            (253) | shutdown | Looper shutting down now...
2016-11-03 21:37:05,684 | DEBUG    | motor.py             (34) | set_status | Claaaa2 changing status from started_hungry to stopping
2016-11-03 21:37:05,684 | INFO     | stacked.py           (82) | stop | stack Claaaa2 stopped
2016-11-03 21:37:05,684 | DEBUG    | motor.py             (34) | set_status | Claaaa2 changing status from stopping to stopped
2016-11-03 21:37:05,684 | INFO     | looper.py            (260) | shutdown | Looper shut down in 0.011 seconds.
2016-11-03 21:37:05,729 | DEBUG    | base_events.py       (410) | close | Close <_UnixSelectorEventLoop running=False closed=False debug=True>
