2016-11-03 21:36:43,309 | INFO     | log.py               (128) | setupLogging | Choosing RAET log level 1
2016-11-03 21:36:45,721 | DEBUG    | testable.py          (126) | decorator | in SpyableTestClient added spy on __init__
2016-11-03 21:36:45,721 | WARNING  | testable.py          (134) | decorator | method <function Client.handleOneNodeMsg at 0x7f505f4c5ea0> not found, so no spy added
2016-11-03 21:36:45,743 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on __init__
2016-11-03 21:36:45,743 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterReqLatencyTooHigh
2016-11-03 21:36:45,743 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterThroughputTooLow
2016-11-03 21:36:45,743 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on sendThroughput
2016-11-03 21:36:45,746 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on __init__
2016-11-03 21:36:45,746 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on catchupCompleted
2016-11-03 21:36:45,746 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on processConsistencyProofReq
2016-11-03 21:36:45,746 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on startCatchUpProcess
2016-11-03 21:36:45,749 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on __init__
2016-11-03 21:36:45,749 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on addToPrePrepares
2016-11-03 21:36:45,749 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canProcessPrePrepare
2016-11-03 21:36:45,749 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canSendPrepare
2016-11-03 21:36:45,750 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doOrder
2016-11-03 21:36:45,750 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrePrepare
2016-11-03 21:36:45,750 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrepare
2016-11-03 21:36:45,750 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on isValidPrepare
2016-11-03 21:36:45,750 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on orderPendingCommit
2016-11-03 21:36:45,750 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processCommit
2016-11-03 21:36:45,750 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrePrepare
2016-11-03 21:36:45,750 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrepare
2016-11-03 21:36:45,766 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on __init__
2016-11-03 21:36:45,766 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on checkPerformance
2016-11-03 21:36:45,766 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on decidePrimaries
2016-11-03 21:36:45,767 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on discard
2016-11-03 21:36:45,767 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on eatTestMsg
2016-11-03 21:36:45,767 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on forward
2016-11-03 21:36:45,775 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleInvalidClientMsg
2016-11-03 21:36:45,775 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleOneNodeMsg
2016-11-03 21:36:45,775 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToClientInBox
2016-11-03 21:36:45,775 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToNodeInBox
2016-11-03 21:36:45,776 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processInstanceChange
2016-11-03 21:36:45,776 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processOrdered
2016-11-03 21:36:45,776 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processPropagate
2016-11-03 21:36:45,776 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processRequest
2016-11-03 21:36:45,776 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on propagate
2016-11-03 21:36:45,776 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousClient
2016-11-03 21:36:45,776 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousNode
2016-11-03 21:36:45,776 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on send
2016-11-03 21:36:45,776 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on sendInstanceChange
2016-11-03 21:36:45,776 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on startViewChange
Loading module /home/lovesh/.virtualenvs/sovrin-dev/lib/python3.5/site-packages/anoncreds_dev-0.1.8-py3.5.egg/config/config-crypto-example1.py
Module loaded.
2016-11-03 21:36:46,377 | DEBUG    | gen_load_ratcheting  (280) | main | Results file: /home/lovesh/dev/evernym/sovrin-priv/scripts/perf_results_1_2_1478189206.csv
2016-11-03 21:36:46,377 | INFO     | gen_load_ratcheting  (136) | _spawnClient | Seed for client Claaaa3 is b'0000000000000000000000000Claaaa3', its len is 32
2016-11-03 21:36:46,380 | DEBUG    | ledger.py            (164) | start | Starting ledger...
2016-11-03 21:36:46,382 | DEBUG    | ledger.py            (69) | recoverTree | Recovering tree from transaction log
2016-11-03 21:36:46,414 | INFO     | client.py            (121) | __init__ | Client Claaaa3 initialized with the following node registry:
2016-11-03 21:36:46,414 | INFO     | client.py            (128) | __init__ |     EvernymV1C      listens at 52.33.22.91    on port 9722
2016-11-03 21:36:46,414 | INFO     | client.py            (128) | __init__ |     EvernymV2C      listens at 52.38.24.189   on port 9724
2016-11-03 21:36:46,414 | INFO     | client.py            (128) | __init__ |     WSECUC          listens at 13.93.218.255  on port 9726
2016-11-03 21:36:46,414 | INFO     | client.py            (128) | __init__ |     BIGC            listens at 52.160.103.164 on port 9728
2016-11-03 21:36:46,414 | INFO     | client.py            (128) | __init__ |     RespectNetworkC listens at 54.173.9.185   on port 9730
2016-11-03 21:36:46,414 | INFO     | client.py            (128) | __init__ |     FCUC            listens at 69.144.146.171 on port 9734
2016-11-03 21:36:46,415 | INFO     | client.py            (128) | __init__ |     BYUC            listens at 54.193.6.155   on port 9745
2016-11-03 21:36:46,415 | DEBUG    | plugin_helper.py     (25) | loadPlugins | Plugin loading started to load plugins from basedir: /home/lovesh/.sovrin
2016-11-03 21:36:47,213 | DEBUG    | plugin_helper.py     (68) | loadPlugins | Total plugins loaded from basedir /home/lovesh/.sovrin are : 1
2016-11-03 21:36:47,213 | DEBUG    | client.py            (148) | __init__ | total plugins loaded in client: 1
2016-11-03 21:36:47,213 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
2016-11-03 21:36:47,213 | DEBUG    | looper.py            (121) | __init__ | Setting handler for SIGINT
2016-11-03 21:36:47,214 | DEBUG    | motor.py             (34) | set_status | Claaaa3 changing status from stopped to starting
2016-11-03 21:36:47,214 | INFO     | stacked.py           (75) | start | stack Claaaa3 starting at ('0.0.0.0', 5961) in always mode
2016-11-03 21:36:47,214 | INFO     | stacked.py           (851) | start | Claaaa3 listening for other nodes at 0.0.0.0:5961
2016-11-03 21:36:47,214 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa3 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:47,214 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa3 nodestack is []
2016-11-03 21:36:47,214 | DEBUG    | stacked.py           (504) | connectToMissing | Claaaa3 found the following missing connections: BIGC, RespectNetworkC, WSECUC, FCUC, EvernymV1C, BYUC, EvernymV2C
2016-11-03 21:36:47,265 | INFO     | stacked.py           (456) | connect | Claaaa3 looking for BIGC at 52.160.103.164:9728
2016-11-03 21:36:47,320 | INFO     | stacked.py           (456) | connect | Claaaa3 looking for RespectNetworkC at 54.173.9.185:9730
2016-11-03 21:36:47,446 | INFO     | stacked.py           (456) | connect | Claaaa3 looking for WSECUC at 13.93.218.255:9726
2016-11-03 21:36:47,887 | INFO     | stacked.py           (456) | connect | Claaaa3 looking for FCUC at 69.144.146.171:9734
2016-11-03 21:36:47,905 | INFO     | stacked.py           (456) | connect | Claaaa3 looking for EvernymV1C at 52.33.22.91:9722
2016-11-03 21:36:47,925 | INFO     | stacked.py           (456) | connect | Claaaa3 looking for BYUC at 54.193.6.155:9745
2016-11-03 21:36:47,944 | INFO     | stacked.py           (456) | connect | Claaaa3 looking for EvernymV2C at 52.38.24.189:9724
2016-11-03 21:36:47,944 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa3 next check for retries in 6.00 seconds
2016-11-03 21:36:47,948 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:48,324 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa3'. Stale transaction '1' packet 'None' from '('54.173.9.185', 9730)' in 1 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '0'
Staler 'Claaaa3'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 1 at 1.912486295994313
Staler 'Claaaa3'. Stale transaction '1' packet 'None' from '('54.193.6.155', 9745)' in 1 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '0'
Staler 'Claaaa3'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 1 at 1.9333146309945732
Staler 'Claaaa3'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '0'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.9526516149999225
Staler 'Claaaa3'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '0'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.9526516149999225
2016-11-03 21:36:48,701 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:48,900 | DEBUG    | stacked.py           (294) | conns | Claaaa3's connection changed from set() to {'BYUC'}
2016-11-03 21:36:48,900 | INFO     | stacked.py           (320) | _connsChanged | Claaaa3 now connected to BYUC
2016-11-03 21:36:48,900 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa3 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BYUC
2016-11-03 21:36:48,934 | DEBUG    | stacked.py           (294) | conns | Claaaa3's connection changed from {'BYUC'} to {'RespectNetworkC', 'BYUC'}
2016-11-03 21:36:48,934 | INFO     | stacked.py           (320) | _connsChanged | Claaaa3 now connected to RespectNetworkC
2016-11-03 21:36:48,934 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa3 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to RespectNetworkC
2016-11-03 21:36:48,978 | DEBUG    | stacked.py           (294) | conns | Claaaa3's connection changed from {'RespectNetworkC', 'BYUC'} to {'RespectNetworkC', 'BYUC', 'EvernymV2C'}
2016-11-03 21:36:48,980 | INFO     | stacked.py           (320) | _connsChanged | Claaaa3 now connected to EvernymV2C
2016-11-03 21:36:48,980 | DEBUG    | motor.py             (34) | set_status | Claaaa3 changing status from starting to started_hungry
2016-11-03 21:36:48,981 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa3 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV2C
Staler 'Claaaa3'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '0'
Staler 'Claaaa3'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.6108522079957766
2016-11-03 21:36:49,054 | DEBUG    | stacked.py           (294) | conns | Claaaa3's connection changed from {'RespectNetworkC', 'BYUC', 'EvernymV2C'} to {'RespectNetworkC', 'BYUC', 'EvernymV2C', 'EvernymV1C'}
2016-11-03 21:36:49,054 | INFO     | stacked.py           (320) | _connsChanged | Claaaa3 now connected to EvernymV1C
2016-11-03 21:36:49,054 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa3 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV1C
2016-11-03 21:36:49,077 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa3'. Stale transaction '3' packet '1' from '('54.193.6.155', 9745)' in 2 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '437'
Staler 'Claaaa3'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 2 at 2.749186490000284
Staler 'Claaaa3'. Stale transaction '3' packet '1' from '('54.173.9.185', 9730)' in 2 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '476'
Staler 'Claaaa3'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 2 at 2.770446598995477
Staler 'Claaaa3'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '0'
Staler 'Claaaa3'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.822974062997673
Staler 'Claaaa3'. Stale transaction '3' packet '1' from '('52.38.24.189', 9724)' in 2 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '485'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 2 at 2.8447065250002197
2016-11-03 21:36:49,282 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa3 got msg from node RespectNetworkC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,283 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa3 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from RespectNetworkC
2016-11-03 21:36:49,283 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa3 cannot start catchup since received only 1 consistency proofs but need at least 3
2016-11-03 21:36:49,302 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa3 got msg from node BYUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,302 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa3 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BYUC
2016-11-03 21:36:49,302 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa3 scheduling action functools.partial(<bound method LedgerManager.checkIfCPsNeeded of Claaaa3>, 0) with id 1 to run in 30 seconds
2016-11-03 21:36:49,302 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa3 cannot start catchup since received only 2 consistency proofs but need at least 3
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('54.193.6.155', 9745)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '437'
Staler 'Claaaa3'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 3 at 3.001932933999342
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('54.173.9.185', 9730)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '476'
Staler 'Claaaa3'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 3 at 3.0200753369936137
2016-11-03 21:36:49,453 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa3'. Stale transaction '3' packet '1' from '('52.33.22.91', 9722)' in 2 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '469'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 2 at 3.052050447993679
2016-11-03 21:36:49,626 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa3 got msg from node EvernymV1C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,631 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa3 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV1C
2016-11-03 21:36:49,631 | DEBUG    | ledger_manager.py    (576) | canStartCatchUpProcess | Claaaa3 deciding on the basis of CPs {'RespectNetworkC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'BYUC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'EvernymV1C': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='])} and f 1
2016-11-03 21:36:49,631 | DEBUG    | ledger_manager.py    (656) | startCatchUpProcess | Claaaa3 started catching up with consistency proof CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=('Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='))
2016-11-03 21:36:49,631 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa3 scheduling action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa3>, 0) with id 2 to run in 5.1 seconds
2016-11-03 21:36:49,632 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa3 sending msg OrderedDict([('op', 'CATCHUP_REQ'), ('ledgerType', 0), ('seqNoStart', 8), ('seqNoEnd', 8)]) to RespectNetworkC
2016-11-03 21:36:49,635 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa3 got msg from node EvernymV2C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,635 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa3 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV2C
2016-11-03 21:36:49,635 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa3 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('52.33.22.91', 9722)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '469'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 3 at 3.244554591998167
2016-11-03 21:36:49,690 | DEBUG    | stacked.py           (294) | conns | Claaaa3's connection changed from {'RespectNetworkC', 'BYUC', 'EvernymV2C', 'EvernymV1C'} to {'RespectNetworkC', 'EvernymV2C', 'BYUC', 'FCUC', 'EvernymV1C'}
2016-11-03 21:36:49,690 | INFO     | stacked.py           (320) | _connsChanged | Claaaa3 now connected to FCUC
2016-11-03 21:36:49,690 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa3 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to FCUC
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('52.38.24.189', 9724)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '485'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 3 at 3.3252982619960676
2016-11-03 21:36:49,831 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:49,897 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa3 got msg from node RespectNetworkC: {'op': 'CATCHUP_REP', 'ledgerType': 0, 'txns': {'8': {'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'reqId': 1478156921805694, 'data': {'node_ip': '40.121.149.41', 'node_port': 9725, 'alias': 'WSECU', 'client_ip': '40.121.149.41', 'client_port': 9726}, 'type': 'CHANGE_HA', 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b'}}, 'consProof': []}
2016-11-03 21:36:49,897 | DEBUG    | ledger_manager.py    (384) | processCatchupRep | Claaaa3 received catchup reply from RespectNetworkC: CATCHUP_REP(ledgerType=0, txns={'8': {'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'reqId': 1478156921805694, 'data': {'node_ip': '40.121.149.41', 'node_port': 9725, 'alias': 'WSECU', 'client_ip': '40.121.149.41', 'client_port': 9726}, 'type': 'CHANGE_HA', 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b'}}, consProof=[])
2016-11-03 21:36:49,897 | DEBUG    | ledger_manager.py    (390) | processCatchupRep | Claaaa3 found 1 transactions in the catchup from RespectNetworkC
2016-11-03 21:36:49,897 | DEBUG    | ledger_manager.py    (399) | processCatchupRep | Claaaa3 merging all received catchups
2016-11-03 21:36:49,897 | DEBUG    | ledger_manager.py    (405) | processCatchupRep | Claaaa3 merged catchups, there are 1 of them now, from 8 to 8
2016-11-03 21:36:49,898 | DEBUG    | ledger_manager.py    (496) | hasValidCatchupReplies | Claaaa3 verifying proof for 8, 8, b'\xc8v\xe37\xc5\xb5\xf0S\x827m\x9d\xe9\xbf\x8b\xc9\xc4\xd7\xaf)\x0b\xb5\xfa\x06\x90\xb1Ed\xb8\xb9ya', b'\xd7\x99p\xfar\xf5\xd9\x9e\xb8\xd2\x05\xe3\x81\x9f\x8c\xdd2;\xfd\xab(\xf6\xbcU\tNW\xc0jDMV', []
2016-11-03 21:36:49,898 | INFO     | ledger_manager.py    (505) | hasValidCatchupReplies | Claaaa3 could not verify catchup reply CATCHUP_REP(ledgerType=0, txns={'8': {'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'reqId': 1478156921805694, 'data': {'node_ip': '40.121.149.41', 'node_port': 9725, 'alias': 'WSECU', 'client_ip': '40.121.149.41', 'client_port': 9726}, 'type': 'CHANGE_HA', 'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b'}}, consProof=[]) since Inconsistency: different root hashes for the same tree size
2016-11-03 21:36:49,898 | DEBUG    | ledger_manager.py    (413) | processCatchupRep | Claaaa3 processed 0 catchup replies with sequence numbers []
Staler 'Claaaa3'. Stale transaction '3' packet '1' from '('69.144.146.171', 9734)' in 2 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '338'
Staler 'Claaaa3'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 2 at 3.4846330159998615
2016-11-03 21:36:50,045 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa3 got msg from node FCUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:50,045 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa3 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from FCUC
2016-11-03 21:36:50,045 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa3 cannot process consistency proof since in state 2 and canSync is True
2016-11-03 21:36:50,207 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('69.144.146.171', 9734)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '338'
Staler 'Claaaa3'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 3 at 3.8493535300003714
2016-11-03 21:36:50,584 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:50,960 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,336 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,720 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,097 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa3'. Stale transaction '1' packet 'None' from '('52.160.103.164', 9728)' in 1 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '0'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 1 at 5.796196590999898
2016-11-03 21:36:52,475 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,851 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,218 | TRACE    | stacked.py           (542) | handleDisconnectedRemote | Claaaa3 allow already in process, so waiting to check for reconnects
2016-11-03 21:36:53,219 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa3 join already in process, so waiting to check for reconnects
2016-11-03 21:36:53,219 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa3 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:53,219 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa3 nodestack is ['BIGC', 'RespectNetworkC', 'estate_8592cf1aa1df11e6ac2c6807152028e4', 'FCUC', 'EvernymV1C', 'BYUC', 'EvernymV2C']
2016-11-03 21:36:53,219 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 2 ('52.160.103.164', 9728)
2016-11-03 21:36:53,219 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 3 ('54.173.9.185', 9730)
2016-11-03 21:36:53,219 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa3 unmatched remote is 4 ('13.93.218.255', 9726)
2016-11-03 21:36:53,220 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa3 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_8592cf1aa1df11e6ac2c6807152028e4
2016-11-03 21:36:53,220 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 5 ('69.144.146.171', 9734)
2016-11-03 21:36:53,220 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 6 ('52.33.22.91', 9722)
2016-11-03 21:36:53,220 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 7 ('54.193.6.155', 9745)
2016-11-03 21:36:53,220 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 8 ('52.38.24.189', 9724)
2016-11-03 21:36:53,220 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa3 next check for retries in 6.00 seconds
2016-11-03 21:36:53,228 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,604 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,981 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,357 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,733 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:54,739 | DEBUG    | has_action_queue.py  (60) | _serviceActions | Claaaa3 running action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa3>, 0) with id 2
2016-11-03 21:36:55,111 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:55,490 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:55,504 | DEBUG    | stacked.py           (294) | conns | Claaaa3's connection changed from {'RespectNetworkC', 'EvernymV2C', 'BYUC', 'FCUC', 'EvernymV1C'} to {'BIGC', 'RespectNetworkC', 'BYUC', 'EvernymV2C', 'FCUC', 'EvernymV1C'}
2016-11-03 21:36:55,504 | INFO     | stacked.py           (320) | _connsChanged | Claaaa3 now connected to BIGC
2016-11-03 21:36:55,504 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa3 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BIGC
2016-11-03 21:36:55,866 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 6 / 7 nodes
2016-11-03 21:36:55,867 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkIfConnectedToAll) succeeded with -0.42 seconds to spare
2016-11-03 21:36:55,869 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'identifier': '6gQVDMNN6JWaMAb1neEQJ47Jhb6HwL3yXczLoyCg4Bt5', 'operation': {'raw': '91679a891bdb2ad936272ec35d94041f41ff987aa02ec46e2c7577599469d049', 'type': 'ATTRIB'}, 'reqId': 1478189215868999, 'signature': None} into identifier:6gQVDMNN6JWaMAb1neEQJ47Jhb6HwL3yXczLoyCg4Bt5|operation:raw:91679a891bdb2ad936272ec35d94041f41ff987aa02ec46e2c7577599469d049|type:ATTRIB|reqId:1478189215868999
2016-11-03 21:36:55,870 | DEBUG    | client.py            (228) | submitReqs | Claaaa3 pending request since in mode 1 and connected to {'BIGC', 'RespectNetworkC', 'BYUC', 'EvernymV2C', 'FCUC', 'EvernymV1C'} nodes
2016-11-03 21:36:55,873 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'raw': '{"17Mq6XjL5f3OgAcanuds_979472": "196886267774_AozjsUn65arPDpewEgJHZ3BV4tiylQu9bcKYdqGkN0IhW8m1fR"}', 'type': 'ATTRIB'}, 'signature': '2o4iP365fK3ezSh4Z1nXYXJTA9CDw72cXppV57LiU2JAXVjkrv4u1jHpVT4NpCMwjPHXrkt5Pb4XgHeZYLKMV7cT', 'identifier': '6gQVDMNN6JWaMAb1neEQJ47Jhb6HwL3yXczLoyCg4Bt5', 'reqId': 1478189215868999}
2016-11-03 21:36:55,874 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa3 sending request Request: {'operation': {'raw': '{"17Mq6XjL5f3OgAcanuds_979472": "196886267774_AozjsUn65arPDpewEgJHZ3BV4tiylQu9bcKYdqGkN0IhW8m1fR"}', 'type': 'ATTRIB'}, 'signature': '2o4iP365fK3ezSh4Z1nXYXJTA9CDw72cXppV57LiU2JAXVjkrv4u1jHpVT4NpCMwjPHXrkt5Pb4XgHeZYLKMV7cT', 'identifier': '6gQVDMNN6JWaMAb1neEQJ47Jhb6HwL3yXczLoyCg4Bt5', 'reqId': 1478189215868999}
Staler 'Claaaa3'. Stale transaction '3' packet '1' from '('52.160.103.164', 9728)' in 2 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '478'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 2 at 11.122042429997236
2016-11-03 21:36:59,221 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa3 join already in process, so waiting to check for reconnects
2016-11-03 21:36:59,221 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa3 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:59,221 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa3 nodestack is ['BIGC', 'RespectNetworkC', 'estate_8592cf1aa1df11e6ac2c6807152028e4', 'FCUC', 'EvernymV1C', 'BYUC', 'EvernymV2C']
2016-11-03 21:36:59,221 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 2 ('52.160.103.164', 9728)
2016-11-03 21:36:59,221 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 3 ('54.173.9.185', 9730)
2016-11-03 21:36:59,222 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa3 unmatched remote is 4 ('13.93.218.255', 9726)
2016-11-03 21:36:59,222 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa3 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_8592cf1aa1df11e6ac2c6807152028e4
2016-11-03 21:36:59,222 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 5 ('69.144.146.171', 9734)
2016-11-03 21:36:59,222 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 6 ('52.33.22.91', 9722)
2016-11-03 21:36:59,222 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 7 ('54.193.6.155', 9745)
2016-11-03 21:36:59,222 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 8 ('52.38.24.189', 9724)
2016-11-03 21:36:59,222 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa3 next check for retries in 6.00 seconds
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '478'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.905413196000154
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '478'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.905413196000154
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '478'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 13.905413196000154
2016-11-03 21:37:00,917 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa3', signerId='6gQVDMNN6JWaMAb1neEQJ47Jhb6HwL3yXczLoyCg4Bt5', reqId=1478189215868999, transactionType='ATTRIB', sentAt=1478189215.8703287, quorumAt='', latency=5.047011852264404, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:00,917 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.46 seconds to spare
2016-11-03 21:37:00,918 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 5.049548625946045
        Average latency: 5.047011852264404
        Throughput: 0.0
        Error rate: 0.19803750277038823
        Succeeded: 0
        Failed: 1
        Query Time: 0
        ================================
        
2016-11-03 21:37:00,918 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'identifier': '6gQVDMNN6JWaMAb1neEQJ47Jhb6HwL3yXczLoyCg4Bt5', 'operation': {'raw': '37d08513bf88a04a131ab38cdd6a87e9583449fd7fe63ce2559ac51e23bad358', 'type': 'ATTRIB'}, 'reqId': 1478189220918283, 'signature': None} into identifier:6gQVDMNN6JWaMAb1neEQJ47Jhb6HwL3yXczLoyCg4Bt5|operation:raw:37d08513bf88a04a131ab38cdd6a87e9583449fd7fe63ce2559ac51e23bad358|type:ATTRIB|reqId:1478189220918283
2016-11-03 21:37:00,918 | DEBUG    | client.py            (228) | submitReqs | Claaaa3 pending request since in mode 1 and connected to {'BIGC', 'RespectNetworkC', 'BYUC', 'EvernymV2C', 'FCUC', 'EvernymV1C'} nodes
2016-11-03 21:37:00,918 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'raw': '{"3XPdnHNxyDgQwsZW8mpi_451124": "827254391586_I6K9YOdUNTvh8o4yCW5x2GlcunQamHAzgp0ftErjPbRVei31MX"}', 'type': 'ATTRIB'}, 'signature': '2NGdzoibzzrfw2JYKAuxG99eKPmH8FyT1wHk58a6qy3LLtvAjQxJYTzstKgdK17EaaoN8sCKvpD7tjoKTUiPwNT8', 'identifier': '6gQVDMNN6JWaMAb1neEQJ47Jhb6HwL3yXczLoyCg4Bt5', 'reqId': 1478189220918283}
2016-11-03 21:37:00,918 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa3 sending request Request: {'operation': {'raw': '{"3XPdnHNxyDgQwsZW8mpi_451124": "827254391586_I6K9YOdUNTvh8o4yCW5x2GlcunQamHAzgp0ftErjPbRVei31MX"}', 'type': 'ATTRIB'}, 'signature': '2NGdzoibzzrfw2JYKAuxG99eKPmH8FyT1wHk58a6qy3LLtvAjQxJYTzstKgdK17EaaoN8sCKvpD7tjoKTUiPwNT8', 'identifier': '6gQVDMNN6JWaMAb1neEQJ47Jhb6HwL3yXczLoyCg4Bt5', 'reqId': 1478189220918283}
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '478'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 15.097539526999753
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '478'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 15.097539526999753
2016-11-03 21:37:01,537 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa3 got msg from node BIGC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:37:01,537 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa3 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BIGC
2016-11-03 21:37:01,537 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa3 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa3'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa3'. Unknown correspondent estate id '478'
Staler 'Claaaa3'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 15.673552317995927
Stalent 'Claaaa3'. Stale transaction '0' packet '0' from '('52.160.103.164', 9728)' in 1 nacking ...
Stalent 'Claaaa3'. Unknown initiator estate id '478'
Stalent 'Claaaa3'. Do Nack of ('52.160.103.164', 9728) in 1 at 15.673552317995927
2016-11-03 21:37:05,233 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa3 join already in process, so waiting to check for reconnects
2016-11-03 21:37:05,233 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa3 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:37:05,234 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa3 nodestack is ['BIGC', 'RespectNetworkC', 'estate_8592cf1aa1df11e6ac2c6807152028e4', 'FCUC', 'EvernymV1C', 'BYUC', 'EvernymV2C']
2016-11-03 21:37:05,234 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 2 ('52.160.103.164', 9728)
2016-11-03 21:37:05,234 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 3 ('54.173.9.185', 9730)
2016-11-03 21:37:05,234 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa3 unmatched remote is 4 ('13.93.218.255', 9726)
2016-11-03 21:37:05,234 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa3 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_8592cf1aa1df11e6ac2c6807152028e4
2016-11-03 21:37:05,235 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 5 ('69.144.146.171', 9734)
2016-11-03 21:37:05,235 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 6 ('52.33.22.91', 9722)
2016-11-03 21:37:05,235 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 7 ('54.193.6.155', 9745)
2016-11-03 21:37:05,235 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa3 matched remote is 8 ('52.38.24.189', 9724)
2016-11-03 21:37:05,235 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa3 next check for retries in 6.00 seconds
2016-11-03 21:37:05,952 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa3', signerId='6gQVDMNN6JWaMAb1neEQJ47Jhb6HwL3yXczLoyCg4Bt5', reqId=1478189220918283, transactionType='ATTRIB', sentAt=1478189220.9186435, quorumAt='', latency=5.033863544464111, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:05,953 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.47 seconds to spare
2016-11-03 21:37:05,956 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 10.08833384513855
        Average latency: 5.040437698364258
        Throughput: 0.0
        Error rate: 0.1982487921891856
        Succeeded: 0
        Failed: 2
        Query Time: 0
        ================================
        
2016-11-03 21:37:05,957 | DEBUG    | gen_load_ratcheting  (326) | main | Sent 1 ATTRIB requests
2016-11-03 21:37:05,957 | INFO     | looper.py            (253) | shutdown | Looper shutting down now...
2016-11-03 21:37:05,968 | DEBUG    | motor.py             (34) | set_status | Claaaa3 changing status from started_hungry to stopping
2016-11-03 21:37:05,969 | INFO     | stacked.py           (82) | stop | stack Claaaa3 stopped
2016-11-03 21:37:05,969 | DEBUG    | motor.py             (34) | set_status | Claaaa3 changing status from stopping to stopped
2016-11-03 21:37:05,969 | INFO     | looper.py            (260) | shutdown | Looper shut down in 0.011 seconds.
2016-11-03 21:37:06,004 | DEBUG    | base_events.py       (410) | close | Close <_UnixSelectorEventLoop running=False closed=False debug=True>
