2016-11-03 21:36:43,571 | INFO     | log.py               (128) | setupLogging | Choosing RAET log level 1
2016-11-03 21:36:46,095 | DEBUG    | testable.py          (126) | decorator | in SpyableTestClient added spy on __init__
2016-11-03 21:36:46,096 | WARNING  | testable.py          (134) | decorator | method <function Client.handleOneNodeMsg at 0x7f2241512ea0> not found, so no spy added
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on __init__
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterReqLatencyTooHigh
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on isMasterThroughputTooLow
2016-11-03 21:36:46,117 | DEBUG    | testable.py          (126) | decorator | in SpyableTestMonitor added spy on sendThroughput
2016-11-03 21:36:46,144 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on __init__
2016-11-03 21:36:46,144 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on catchupCompleted
2016-11-03 21:36:46,144 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on processConsistencyProofReq
2016-11-03 21:36:46,144 | DEBUG    | testable.py          (126) | decorator | in SpyableTestLedgerManager added spy on startCatchUpProcess
2016-11-03 21:36:46,147 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on __init__
2016-11-03 21:36:46,148 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on addToPrePrepares
2016-11-03 21:36:46,148 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canProcessPrePrepare
2016-11-03 21:36:46,148 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on canSendPrepare
2016-11-03 21:36:46,148 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doOrder
2016-11-03 21:36:46,148 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrePrepare
2016-11-03 21:36:46,148 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on doPrepare
2016-11-03 21:36:46,148 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on isValidPrepare
2016-11-03 21:36:46,148 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on orderPendingCommit
2016-11-03 21:36:46,148 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processCommit
2016-11-03 21:36:46,149 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrePrepare
2016-11-03 21:36:46,149 | DEBUG    | testable.py          (126) | decorator | in SpyableTestReplica added spy on processPrepare
2016-11-03 21:36:46,152 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on __init__
2016-11-03 21:36:46,152 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on checkPerformance
2016-11-03 21:36:46,153 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on decidePrimaries
2016-11-03 21:36:46,153 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on discard
2016-11-03 21:36:46,153 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on eatTestMsg
2016-11-03 21:36:46,153 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on forward
2016-11-03 21:36:46,153 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleInvalidClientMsg
2016-11-03 21:36:46,153 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on handleOneNodeMsg
2016-11-03 21:36:46,153 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToClientInBox
2016-11-03 21:36:46,153 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on postToNodeInBox
2016-11-03 21:36:46,153 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processInstanceChange
2016-11-03 21:36:46,154 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processOrdered
2016-11-03 21:36:46,154 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processPropagate
2016-11-03 21:36:46,154 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on processRequest
2016-11-03 21:36:46,154 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on propagate
2016-11-03 21:36:46,154 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousClient
2016-11-03 21:36:46,154 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on reportSuspiciousNode
2016-11-03 21:36:46,154 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on send
2016-11-03 21:36:46,154 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on sendInstanceChange
2016-11-03 21:36:46,154 | DEBUG    | testable.py          (126) | decorator | in SpyableTestNode added spy on startViewChange
Loading module /home/lovesh/.virtualenvs/sovrin-dev/lib/python3.5/site-packages/anoncreds_dev-0.1.8-py3.5.egg/config/config-crypto-example1.py
Module loaded.
2016-11-03 21:36:46,716 | DEBUG    | gen_load_ratcheting  (280) | main | Results file: /home/lovesh/dev/evernym/sovrin-priv/scripts/perf_results_1_2_1478189206.csv
2016-11-03 21:36:46,716 | INFO     | gen_load_ratcheting  (136) | _spawnClient | Seed for client Claaaa5 is b'0000000000000000000000000Claaaa5', its len is 32
2016-11-03 21:36:46,717 | DEBUG    | ledger.py            (164) | start | Starting ledger...
2016-11-03 21:36:46,717 | DEBUG    | ledger.py            (69) | recoverTree | Recovering tree from transaction log
2016-11-03 21:36:46,749 | INFO     | client.py            (121) | __init__ | Client Claaaa5 initialized with the following node registry:
2016-11-03 21:36:46,749 | INFO     | client.py            (128) | __init__ |     EvernymV1C      listens at 52.33.22.91    on port 9722
2016-11-03 21:36:46,749 | INFO     | client.py            (128) | __init__ |     EvernymV2C      listens at 52.38.24.189   on port 9724
2016-11-03 21:36:46,749 | INFO     | client.py            (128) | __init__ |     WSECUC          listens at 13.93.218.255  on port 9726
2016-11-03 21:36:46,749 | INFO     | client.py            (128) | __init__ |     BIGC            listens at 52.160.103.164 on port 9728
2016-11-03 21:36:46,749 | INFO     | client.py            (128) | __init__ |     RespectNetworkC listens at 54.173.9.185   on port 9730
2016-11-03 21:36:46,749 | INFO     | client.py            (128) | __init__ |     FCUC            listens at 69.144.146.171 on port 9734
2016-11-03 21:36:46,749 | INFO     | client.py            (128) | __init__ |     BYUC            listens at 54.193.6.155   on port 9745
2016-11-03 21:36:46,749 | DEBUG    | plugin_helper.py     (25) | loadPlugins | Plugin loading started to load plugins from basedir: /home/lovesh/.sovrin
2016-11-03 21:36:47,233 | DEBUG    | plugin_helper.py     (68) | loadPlugins | Total plugins loaded from basedir /home/lovesh/.sovrin are : 1
2016-11-03 21:36:47,233 | DEBUG    | client.py            (148) | __init__ | total plugins loaded in client: 1
2016-11-03 21:36:47,233 | DEBUG    | selector_events.py   (53) | __init__ | Using selector: EpollSelector
2016-11-03 21:36:47,233 | DEBUG    | looper.py            (121) | __init__ | Setting handler for SIGINT
2016-11-03 21:36:47,234 | DEBUG    | motor.py             (34) | set_status | Claaaa5 changing status from stopped to starting
2016-11-03 21:36:47,234 | INFO     | stacked.py           (75) | start | stack Claaaa5 starting at ('0.0.0.0', 6244) in always mode
2016-11-03 21:36:47,234 | INFO     | stacked.py           (851) | start | Claaaa5 listening for other nodes at 0.0.0.0:6244
2016-11-03 21:36:47,234 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa5 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:47,234 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa5 nodestack is []
2016-11-03 21:36:47,234 | DEBUG    | stacked.py           (504) | connectToMissing | Claaaa5 found the following missing connections: EvernymV1C, RespectNetworkC, EvernymV2C, BYUC, BIGC, FCUC, WSECUC
2016-11-03 21:36:47,289 | INFO     | stacked.py           (456) | connect | Claaaa5 looking for EvernymV1C at 52.33.22.91:9722
2016-11-03 21:36:47,341 | INFO     | stacked.py           (456) | connect | Claaaa5 looking for RespectNetworkC at 54.173.9.185:9730
2016-11-03 21:36:47,394 | INFO     | stacked.py           (456) | connect | Claaaa5 looking for EvernymV2C at 52.38.24.189:9724
2016-11-03 21:36:47,449 | INFO     | stacked.py           (456) | connect | Claaaa5 looking for BYUC at 54.193.6.155:9745
2016-11-03 21:36:47,502 | INFO     | stacked.py           (456) | connect | Claaaa5 looking for BIGC at 52.160.103.164:9728
2016-11-03 21:36:47,555 | INFO     | stacked.py           (456) | connect | Claaaa5 looking for FCUC at 69.144.146.171:9734
2016-11-03 21:36:47,575 | INFO     | stacked.py           (456) | connect | Claaaa5 looking for WSECUC at 13.93.218.255:9726
2016-11-03 21:36:47,575 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa5 next check for retries in 6.00 seconds
2016-11-03 21:36:47,578 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
2016-11-03 21:36:47,955 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa5'. Stale transaction '1' packet 'None' from '('54.193.6.155', 9745)' in 1 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '0'
Staler 'Claaaa5'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 1 at 1.4252287430063006
Staler 'Claaaa5'. Stale transaction '1' packet 'None' from '('54.173.9.185', 9730)' in 1 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '0'
Staler 'Claaaa5'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 1 at 1.4252287430063006
Staler 'Claaaa5'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '0'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.487655586002802
Staler 'Claaaa5'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '0'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.487655586002802
Staler 'Claaaa5'. Stale transaction '1' packet 'None' from '('54.193.6.155', 9745)' in 1 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '0'
Staler 'Claaaa5'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 1 at 1.5308003620011732
Staler 'Claaaa5'. Stale transaction '1' packet 'None' from '('54.173.9.185', 9730)' in 1 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '0'
Staler 'Claaaa5'. Do Nack of stale correspondent ('54.173.9.185', 9730) in 1 at 1.5748040969992871
2016-11-03 21:36:48,335 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 0 / 7 nodes
Staler 'Claaaa5'. Stale transaction '1' packet 'None' from '('52.38.24.189', 9724)' in 1 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '0'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 1 at 1.6110143640034948
Staler 'Claaaa5'. Stale transaction '1' packet 'None' from '('52.33.22.91', 9722)' in 1 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '0'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 1 at 1.6329987499993877
2016-11-03 21:36:48,640 | DEBUG    | stacked.py           (294) | conns | Claaaa5's connection changed from set() to {'BYUC'}
2016-11-03 21:36:48,640 | INFO     | stacked.py           (320) | _connsChanged | Claaaa5 now connected to BYUC
2016-11-03 21:36:48,640 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa5 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BYUC
2016-11-03 21:36:48,689 | DEBUG    | stacked.py           (294) | conns | Claaaa5's connection changed from {'BYUC'} to {'RespectNetworkC', 'BYUC'}
2016-11-03 21:36:48,689 | INFO     | stacked.py           (320) | _connsChanged | Claaaa5 now connected to RespectNetworkC
2016-11-03 21:36:48,689 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa5 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to RespectNetworkC
2016-11-03 21:36:48,711 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 2 / 7 nodes
2016-11-03 21:36:48,811 | DEBUG    | stacked.py           (294) | conns | Claaaa5's connection changed from {'RespectNetworkC', 'BYUC'} to {'EvernymV1C', 'RespectNetworkC', 'BYUC'}
2016-11-03 21:36:48,812 | INFO     | stacked.py           (320) | _connsChanged | Claaaa5 now connected to EvernymV1C
2016-11-03 21:36:48,812 | DEBUG    | motor.py             (34) | set_status | Claaaa5 changing status from starting to started_hungry
2016-11-03 21:36:48,812 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa5 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV1C
2016-11-03 21:36:48,833 | DEBUG    | stacked.py           (294) | conns | Claaaa5's connection changed from {'EvernymV1C', 'RespectNetworkC', 'BYUC'} to {'EvernymV1C', 'RespectNetworkC', 'EvernymV2C', 'BYUC'}
2016-11-03 21:36:48,833 | INFO     | stacked.py           (320) | _connsChanged | Claaaa5 now connected to EvernymV2C
2016-11-03 21:36:48,833 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa5 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to EvernymV2C
Staler 'Claaaa5'. Stale transaction '1' packet 'None' from '('69.144.146.171', 9734)' in 1 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '0'
Staler 'Claaaa5'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 1 at 2.121499209999456
2016-11-03 21:36:48,992 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa5 got msg from node BYUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:48,992 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa5 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BYUC
2016-11-03 21:36:48,993 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa5 cannot start catchup since received only 1 consistency proofs but need at least 3
2016-11-03 21:36:49,032 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa5 got msg from node RespectNetworkC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,032 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa5 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from RespectNetworkC
2016-11-03 21:36:49,033 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa5 scheduling action functools.partial(<bound method LedgerManager.checkIfCPsNeeded of Claaaa5>, 0) with id 1 to run in 30 seconds
2016-11-03 21:36:49,033 | DEBUG    | ledger_manager.py    (591) | canStartCatchUpProcess | Claaaa5 cannot start catchup since received only 2 consistency proofs but need at least 3
Staler 'Claaaa5'. Stale transaction '3' packet '1' from '('52.38.24.189', 9724)' in 2 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '479'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 2 at 2.3315277389992843
Staler 'Claaaa5'. Stale transaction '3' packet '1' from '('52.33.22.91', 9722)' in 2 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '463'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 2 at 2.3315277389992843
2016-11-03 21:36:49,093 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 4 / 7 nodes
Staler 'Claaaa5'. Stale transaction '4' packet '1' from '('54.193.6.155', 9745)' in 3 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '431'
Staler 'Claaaa5'. Do Nack of stale correspondent ('54.193.6.155', 9745) in 3 at 2.50371412000095
2016-11-03 21:36:49,306 | DEBUG    | stacked.py           (294) | conns | Claaaa5's connection changed from {'EvernymV1C', 'RespectNetworkC', 'EvernymV2C', 'BYUC'} to {'FCUC', 'EvernymV1C', 'RespectNetworkC', 'EvernymV2C', 'BYUC'}
2016-11-03 21:36:49,306 | INFO     | stacked.py           (320) | _connsChanged | Claaaa5 now connected to FCUC
2016-11-03 21:36:49,307 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa5 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to FCUC
2016-11-03 21:36:49,322 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa5 got msg from node EvernymV1C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,322 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa5 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV1C
2016-11-03 21:36:49,322 | DEBUG    | ledger_manager.py    (576) | canStartCatchUpProcess | Claaaa5 deciding on the basis of CPs {'EvernymV1C': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'RespectNetworkC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']), 'BYUC': CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='])} and f 1
2016-11-03 21:36:49,322 | DEBUG    | ledger_manager.py    (656) | startCatchUpProcess | Claaaa5 started catching up with consistency proof CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=('Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY='))
2016-11-03 21:36:49,323 | DEBUG    | has_action_queue.py  (30) | _schedule | Claaaa5 scheduling action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa5>, 0) with id 2 to run in 5.1 seconds
2016-11-03 21:36:49,323 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa5 sending msg OrderedDict([('op', 'CATCHUP_REQ'), ('ledgerType', 0), ('seqNoStart', 8), ('seqNoEnd', 8)]) to FCUC
2016-11-03 21:36:49,424 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa5 got msg from node EvernymV2C: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,424 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa5 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from EvernymV2C
2016-11-03 21:36:49,424 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa5 cannot process consistency proof since in state 2 and canSync is True
Staler 'Claaaa5'. Stale transaction '3' packet '1' from '('69.144.146.171', 9734)' in 2 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '332'
Staler 'Claaaa5'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 2 at 2.702529330003017
2016-11-03 21:36:49,470 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa5'. Stale transaction '4' packet '1' from '('52.33.22.91', 9722)' in 3 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '463'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.33.22.91', 9722) in 3 at 2.726683088003483
Staler 'Claaaa5'. Stale transaction '4' packet '1' from '('52.38.24.189', 9724)' in 3 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '479'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.38.24.189', 9724) in 3 at 2.8829161070025293
Staler 'Claaaa5'. Stale transaction '1' packet 'None' from '('52.160.103.164', 9728)' in 1 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '0'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 1 at 2.903266491004615
2016-11-03 21:36:49,682 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa5 got msg from node FCUC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:49,683 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa5 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from FCUC
2016-11-03 21:36:49,683 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa5 cannot process consistency proof since in state 2 and canSync is True
2016-11-03 21:36:49,683 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa5 got msg from node FCUC: {'op': 'CATCHUP_REP', 'ledgerType': 0, 'txns': {'8': {'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'type': 'CHANGE_HA', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'node_ip': '40.121.149.41', 'client_port': 9726, 'alias': 'WSECU'}, 'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'reqId': 1478156921805694}}, 'consProof': []}
2016-11-03 21:36:49,683 | DEBUG    | ledger_manager.py    (384) | processCatchupRep | Claaaa5 received catchup reply from FCUC: CATCHUP_REP(ledgerType=0, txns={'8': {'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'type': 'CHANGE_HA', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'node_ip': '40.121.149.41', 'client_port': 9726, 'alias': 'WSECU'}, 'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'reqId': 1478156921805694}}, consProof=[])
2016-11-03 21:36:49,683 | DEBUG    | ledger_manager.py    (390) | processCatchupRep | Claaaa5 found 1 transactions in the catchup from FCUC
2016-11-03 21:36:49,684 | DEBUG    | ledger_manager.py    (399) | processCatchupRep | Claaaa5 merging all received catchups
2016-11-03 21:36:49,684 | DEBUG    | ledger_manager.py    (405) | processCatchupRep | Claaaa5 merged catchups, there are 1 of them now, from 8 to 8
2016-11-03 21:36:49,684 | DEBUG    | ledger_manager.py    (496) | hasValidCatchupReplies | Claaaa5 verifying proof for 8, 8, b'\xc8v\xe37\xc5\xb5\xf0S\x827m\x9d\xe9\xbf\x8b\xc9\xc4\xd7\xaf)\x0b\xb5\xfa\x06\x90\xb1Ed\xb8\xb9ya', b'\xd7\x99p\xfar\xf5\xd9\x9e\xb8\xd2\x05\xe3\x81\x9f\x8c\xdd2;\xfd\xab(\xf6\xbcU\tNW\xc0jDMV', []
2016-11-03 21:36:49,684 | INFO     | ledger_manager.py    (505) | hasValidCatchupReplies | Claaaa5 could not verify catchup reply CATCHUP_REP(ledgerType=0, txns={'8': {'txnId': 'bfa9e020f5963c12132024d5a2067c2bd6f53b5244cf247e9e50872c9249704b', 'type': 'CHANGE_HA', 'identifier': 'CECeGXDi6EHuhpwz19uyjjEnsRGNXodFYqCRgdLmLRkt', 'data': {'node_port': 9725, 'client_ip': '40.121.149.41', 'node_ip': '40.121.149.41', 'client_port': 9726, 'alias': 'WSECU'}, 'txnTime': 1478157003369.697, 'dest': 'AZsp46qSPGjHuNYajiMUb5XcMWCRDuk2xdEv7P5MepSN', 'reqId': 1478156921805694}}, consProof=[]) since Inconsistency: different root hashes for the same tree size
2016-11-03 21:36:49,684 | DEBUG    | ledger_manager.py    (413) | processCatchupRep | Claaaa5 processed 0 catchup replies with sequence numbers []
2016-11-03 21:36:49,851 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
Staler 'Claaaa5'. Stale transaction '4' packet '1' from '('69.144.146.171', 9734)' in 3 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '332'
Staler 'Claaaa5'. Do Nack of stale correspondent ('69.144.146.171', 9734) in 3 at 3.1047008740060846
2016-11-03 21:36:50,227 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:50,604 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:50,980 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,357 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:51,734 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,110 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,487 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:52,863 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 5 / 7 nodes
2016-11-03 21:36:53,144 | DEBUG    | stacked.py           (294) | conns | Claaaa5's connection changed from {'FCUC', 'EvernymV1C', 'RespectNetworkC', 'EvernymV2C', 'BYUC'} to {'EvernymV1C', 'RespectNetworkC', 'BYUC', 'FCUC', 'EvernymV2C', 'BIGC'}
2016-11-03 21:36:53,144 | INFO     | stacked.py           (320) | _connsChanged | Claaaa5 now connected to BIGC
2016-11-03 21:36:53,144 | TRACE    | stacked.py           (775) | flushOutBoxes | Claaaa5 sending msg OrderedDict([('op', 'LEDGER_STATUS'), ('ledgerType', 0), ('txnSeqNo', 7), ('merkleRoot', 'O+RcXjejV+qOWuxtS2jn+6QGSrZm7B52Cy87P2UBOik=')]) to BIGC
2016-11-03 21:36:53,240 | DEBUG    | gen_load_ratcheting  (216) | checkIfConnectedToAll | Connected 6 / 7 nodes
2016-11-03 21:36:53,240 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkIfConnectedToAll) succeeded with 1.84 seconds to spare
2016-11-03 21:36:53,242 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'operation': {'type': 'ATTRIB', 'raw': 'ca1a7a4aadd5cc931a3424de0e3b86d6886aac103445fba04ac8ab29c065b523'}, 'reqId': 1478189213241743, 'identifier': '36xFDCvKyJR1hLYShq2BptVfBUNbJ9JkZTVeQDWcrsVz', 'signature': None} into identifier:36xFDCvKyJR1hLYShq2BptVfBUNbJ9JkZTVeQDWcrsVz|operation:raw:ca1a7a4aadd5cc931a3424de0e3b86d6886aac103445fba04ac8ab29c065b523|type:ATTRIB|reqId:1478189213241743
2016-11-03 21:36:53,245 | DEBUG    | client.py            (228) | submitReqs | Claaaa5 pending request since in mode 1 and connected to {'EvernymV1C', 'RespectNetworkC', 'BYUC', 'FCUC', 'EvernymV2C', 'BIGC'} nodes
2016-11-03 21:36:53,245 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'type': 'ATTRIB', 'raw': '{"0XpZNFlqQjh9KBnby3Yv_212471": "447001902439_ScGJFayMObiNKBpHvklL8x6XTdEUz25QqhZ3onm1YVj7greWfR"}'}, 'signature': '2i4gUuRxTc7AVXWD7PRsF9ZW8gG9FXGXe89Qaazc548dS5rn6Yr9bjQDhfrXoGQnU4ZaKqmyfMFcUm8ubtBqmNhi', 'reqId': 1478189213241743, 'identifier': '36xFDCvKyJR1hLYShq2BptVfBUNbJ9JkZTVeQDWcrsVz'}
2016-11-03 21:36:53,246 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa5 sending request Request: {'operation': {'type': 'ATTRIB', 'raw': '{"0XpZNFlqQjh9KBnby3Yv_212471": "447001902439_ScGJFayMObiNKBpHvklL8x6XTdEUz25QqhZ3onm1YVj7greWfR"}'}, 'signature': '2i4gUuRxTc7AVXWD7PRsF9ZW8gG9FXGXe89Qaazc548dS5rn6Yr9bjQDhfrXoGQnU4ZaKqmyfMFcUm8ubtBqmNhi', 'reqId': 1478189213241743, 'identifier': '36xFDCvKyJR1hLYShq2BptVfBUNbJ9JkZTVeQDWcrsVz'}
2016-11-03 21:36:53,248 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa5 join already in process, so waiting to check for reconnects
2016-11-03 21:36:53,249 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa5 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:53,249 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa5 nodestack is ['EvernymV1C', 'RespectNetworkC', 'EvernymV2C', 'BYUC', 'BIGC', 'FCUC', 'estate_8595dce0a1df11e6ac2c6807152028e4']
2016-11-03 21:36:53,249 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 2 ('52.33.22.91', 9722)
2016-11-03 21:36:53,249 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 3 ('54.173.9.185', 9730)
2016-11-03 21:36:53,249 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 4 ('52.38.24.189', 9724)
2016-11-03 21:36:53,249 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 5 ('54.193.6.155', 9745)
2016-11-03 21:36:53,250 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 6 ('52.160.103.164', 9728)
2016-11-03 21:36:53,250 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 7 ('69.144.146.171', 9734)
2016-11-03 21:36:53,250 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa5 unmatched remote is 8 ('13.93.218.255', 9726)
2016-11-03 21:36:53,250 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa5 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_8595dce0a1df11e6ac2c6807152028e4
2016-11-03 21:36:53,250 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa5 next check for retries in 6.00 seconds
Staler 'Claaaa5'. Stale transaction '3' packet '1' from '('52.160.103.164', 9728)' in 2 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '472'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 2 at 7.246664877005969
2016-11-03 21:36:54,433 | DEBUG    | has_action_queue.py  (60) | _serviceActions | Claaaa5 running action functools.partial(<bound method LedgerManager.checkIfTxnsNeeded of Claaaa5>, 0) with id 2
Staler 'Claaaa5'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '472'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 8.7367628800057
Staler 'Claaaa5'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '472'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 10.784923259001516
Staler 'Claaaa5'. Stale transaction '4' packet '1' from '('52.160.103.164', 9728)' in 3 nacking...
Staler 'Claaaa5'. Unknown correspondent estate id '472'
Staler 'Claaaa5'. Do Nack of stale correspondent ('52.160.103.164', 9728) in 3 at 10.784923259001516
2016-11-03 21:36:57,559 | DEBUG    | client.py            (249) | handleOneNodeMsg | Client Claaaa5 got msg from node BIGC: {'op': 'CONSISTENCY_PROOF', 'ledgerType': 0, 'seqNoStart': 7, 'seqNoEnd': 8, 'oldMerkleRoot': 'Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', 'newMerkleRoot': '15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', 'hashes': ['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']}
2016-11-03 21:36:57,559 | DEBUG    | ledger_manager.py    (310) | processConsistencyProof | Claaaa5 received consistency proof: CONSISTENCY_PROOF(ledgerType=0, seqNoStart=7, seqNoEnd=8, oldMerkleRoot='Ym2M5MCcYtL9Nhl+JinisTVwK4iCDbU+mcKedj+pYLY=', newMerkleRoot='15lw+nL12Z640gXjgZ+M3TI7/aso9rxVCU5XwGpETVY=', hashes=['Kk5CspFcrPDCFrch/iflg1tXS3Htv3H7o6vUYeY9m0U=', 'gpkiCCgaoZdRd6QBalKTGMK4WsVMHGDirI8tH3DCGG8=', 'qNa3BH7CvBHjSAJJ+BXqzy1Bd3aDInGyB9IeS5fpCdI=', 'tXipkaSw3qcSHcCk8LEqSxd0UWgELv40mIs8OZgCImY=']) from BIGC
2016-11-03 21:36:57,560 | DEBUG    | ledger_manager.py    (344) | canProcessConsistencyProof | Claaaa5 cannot process consistency proof since in state 2 and canSync is True
2016-11-03 21:36:58,323 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa5', signerId='36xFDCvKyJR1hLYShq2BptVfBUNbJ9JkZTVeQDWcrsVz', reqId=1478189213241743, transactionType='ATTRIB', sentAt=1478189213.2432704, quorumAt='', latency=5.080170154571533, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:36:58,324 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.42 seconds to spare
2016-11-03 21:36:58,324 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 5.083746433258057
        Average latency: 5.080170154571533
        Throughput: 0.0
        Error rate: 0.19670532610713296
        Succeeded: 0
        Failed: 1
        Query Time: 0
        ================================
        
2016-11-03 21:36:58,325 | TRACE    | signing.py           (86) | serializeMsg | serialized msg {'operation': {'type': 'ATTRIB', 'raw': '10117e4ed755a398ce01b5beeaf7ebe289cf8f3c580dc73cc68851eb25375a66'}, 'reqId': 1478189218325481, 'identifier': '36xFDCvKyJR1hLYShq2BptVfBUNbJ9JkZTVeQDWcrsVz', 'signature': None} into identifier:36xFDCvKyJR1hLYShq2BptVfBUNbJ9JkZTVeQDWcrsVz|operation:raw:10117e4ed755a398ce01b5beeaf7ebe289cf8f3c580dc73cc68851eb25375a66|type:ATTRIB|reqId:1478189218325481
2016-11-03 21:36:58,326 | DEBUG    | client.py            (228) | submitReqs | Claaaa5 pending request since in mode 1 and connected to {'EvernymV1C', 'RespectNetworkC', 'BYUC', 'FCUC', 'EvernymV2C', 'BIGC'} nodes
2016-11-03 21:36:58,326 | DEBUG    | client.py            (416) | pendReqsTillConnection | Enqueuing request since not enough connections with nodes: Request: {'operation': {'type': 'ATTRIB', 'raw': '{"U1AasjgOB36RH8eKcIDr_913420": "483069648521_dJFn2CD0iHMe1pzITPYRkV3olt4UxhSXWOvj5ZbEqyAfB7Q9mG"}'}, 'signature': 'QtpXZU8pkNgo3PbGeUW6PPYAUi1ydCWG3JnK5qq6LMBs4D2nGU8fsCCxH9SZ8BJ7htuRPiGqksv1Fax5gY7Qwdm', 'reqId': 1478189218325481, 'identifier': '36xFDCvKyJR1hLYShq2BptVfBUNbJ9JkZTVeQDWcrsVz'}
2016-11-03 21:36:58,326 | DEBUG    | gen_load_ratcheting  (123) | _submit | Client Claaaa5 sending request Request: {'operation': {'type': 'ATTRIB', 'raw': '{"U1AasjgOB36RH8eKcIDr_913420": "483069648521_dJFn2CD0iHMe1pzITPYRkV3olt4UxhSXWOvj5ZbEqyAfB7Q9mG"}'}, 'signature': 'QtpXZU8pkNgo3PbGeUW6PPYAUi1ydCWG3JnK5qq6LMBs4D2nGU8fsCCxH9SZ8BJ7htuRPiGqksv1Fax5gY7Qwdm', 'reqId': 1478189218325481, 'identifier': '36xFDCvKyJR1hLYShq2BptVfBUNbJ9JkZTVeQDWcrsVz'}
2016-11-03 21:36:59,250 | TRACE    | stacked.py           (534) | handleDisconnectedRemote | Claaaa5 join already in process, so waiting to check for reconnects
2016-11-03 21:36:59,250 | DEBUG    | stacked.py           (625) | reconcileNodeReg | Claaaa5 nodereg is odict_items([('EvernymV1C', HA(host='52.33.22.91', port=9722)), ('EvernymV2C', HA(host='52.38.24.189', port=9724)), ('WSECUC', HA(host='13.93.218.255', port=9726)), ('BIGC', HA(host='52.160.103.164', port=9728)), ('RespectNetworkC', HA(host='54.173.9.185', port=9730)), ('FCUC', HA(host='69.144.146.171', port=9734)), ('BYUC', HA(host='54.193.6.155', port=9745))])
2016-11-03 21:36:59,250 | DEBUG    | stacked.py           (627) | reconcileNodeReg | Claaaa5 nodestack is ['EvernymV1C', 'RespectNetworkC', 'EvernymV2C', 'BYUC', 'BIGC', 'FCUC', 'estate_8595dce0a1df11e6ac2c6807152028e4']
2016-11-03 21:36:59,253 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 2 ('52.33.22.91', 9722)
2016-11-03 21:36:59,253 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 3 ('54.173.9.185', 9730)
2016-11-03 21:36:59,253 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 4 ('52.38.24.189', 9724)
2016-11-03 21:36:59,253 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 5 ('54.193.6.155', 9745)
2016-11-03 21:36:59,253 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 6 ('52.160.103.164', 9728)
2016-11-03 21:36:59,253 | DEBUG    | stacked.py           (633) | reconcileNodeReg | Claaaa5 matched remote is 7 ('69.144.146.171', 9734)
2016-11-03 21:36:59,253 | DEBUG    | stacked.py           (651) | reconcileNodeReg | Claaaa5 unmatched remote is 8 ('13.93.218.255', 9726)
2016-11-03 21:36:59,254 | DEBUG    | stacked.py           (655) | reconcileNodeReg | Claaaa5 forgiving name mismatch for WSECUC with same ha ('13.93.218.255', 9726) using another name estate_8595dce0a1df11e6ac2c6807152028e4
2016-11-03 21:36:59,254 | DEBUG    | stacked.py           (490) | maintainConnections | Claaaa5 next check for retries in 6.00 seconds
Stalent 'Claaaa5'. Stale transaction '0' packet '0' from '('52.160.103.164', 9728)' in 1 nacking ...
Stalent 'Claaaa5'. Unknown initiator estate id '472'
Stalent 'Claaaa5'. Do Nack of ('52.160.103.164', 9728) in 1 at 13.567199819000962
2016-11-03 21:37:03,378 | DEBUG    | gen_load_ratcheting  (206) | checkReplyAndLogStat | COUNTER ResultRow(signerName='Claaaa5', signerId='36xFDCvKyJR1hLYShq2BptVfBUNbJ9JkZTVeQDWcrsVz', reqId=1478189218325481, transactionType='ATTRIB', sentAt=1478189218.3262415, quorumAt='', latency=5.052079200744629, ackNodes='', nackNodes='', replyNodes='')
2016-11-03 21:37:03,378 | DEBUG    | eventually.py        (86) | eventuallyAll | partial(checkReplyAndLogStat) succeeded with 2.45 seconds to spare
2016-11-03 21:37:03,379 | DEBUG    | gen_load_ratcheting  (269) | printCurrentTestResults | 
        ================================
        Test time: 10.138339042663574
        Average latency: 5.066124677658081
        Throughput: 0.0
        Error rate: 0.19727097225528908
        Succeeded: 0
        Failed: 2
        Query Time: 0
        ================================
        
2016-11-03 21:37:03,379 | DEBUG    | gen_load_ratcheting  (326) | main | Sent 1 ATTRIB requests
2016-11-03 21:37:03,379 | INFO     | looper.py            (253) | shutdown | Looper shutting down now...
2016-11-03 21:37:03,386 | DEBUG    | motor.py             (34) | set_status | Claaaa5 changing status from started_hungry to stopping
2016-11-03 21:37:03,387 | INFO     | stacked.py           (82) | stop | stack Claaaa5 stopped
2016-11-03 21:37:03,387 | DEBUG    | motor.py             (34) | set_status | Claaaa5 changing status from stopping to stopped
2016-11-03 21:37:03,387 | INFO     | looper.py            (260) | shutdown | Looper shut down in 0.007 seconds.
2016-11-03 21:37:03,426 | DEBUG    | base_events.py       (410) | close | Close <_UnixSelectorEventLoop running=False closed=False debug=True>
